workflows:
  android-release:
    name: Study Bee Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
